[package]
name = "capybara-packet-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
winnow = {version = "0.6.7"}
uuid = "1.8"
serde = "1"
