[package]
name = "capybara-nbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = {version = "0.5"}
flate2 = "1.0.28"
