[package]
name = "capybara-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.10.14"
bevy = {version = "0.10.1", default-features=false}
tokio = {version = "1.23.0", features=["full"]}
bytes = "1.4.0"
anyhow = "1.0.71"
thiserror = "1.0.40"
uuid = "1.3.2"

# Log
log = "0.4.17"

fern = "0.6.2"
humantime = "2.1.0"

capybara-packet = { path = '../capybara-packet'}