[package]
name = "capybara"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.37.0", features=["full" ]}

capybara-packet = {path = "../capybara-packet"}
capybara-ecs = {path = "../capybara-ecs"}
