[package]
name = "capybara"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.33.0", features=["full" ]}

capybara-macros = {path = '../capybara-macros'}
capybara-packet = {path = "../capybara-packet"}
capybara-ecs = {path = "../capybara-ecs"}
